app = "zhorben-elysium-6a97b853-09d2-4d1a-b3fe-108723a35218"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'
DEPLOY_ID = 'cbc815f9-f323-4291-bba7-66276b53bca3'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
